#### Import Data

In [15]:
import pandas_ta as ta

In [1]:
import pandas as pd
df = pd.read_csv('btc_1hour_cleaned.csv')

In [2]:
df.head()

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
0,2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999,5.993910e+06,5228,228.521921,3.090541e+06,0
1,2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999,5.154522e+06,4534,180.840403,2.430449e+06,0
2,2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999,5.710192e+06,4887,192.237935,2.558505e+06,0
3,2018-01-01 03:00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999,5.657448e+06,4789,137.918407,1.858041e+06,0
4,2018-01-01 04:00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999,4.588047e+06,4563,172.957635,2.328058e+06,0

In [3]:
df.dtypes

Open time                           str
Open                            float64
High                            float64
Low                             float64
Close                           float64
Volume                          float64
Close time                          str
Quote asset volume              float64
Number of trades                  int64
Taker buy base asset volume     float64
Taker buy quote asset volume    float64
Ignore                            int64
dtype: object

In [4]:

df["Open time"] = pd.to_datetime(df["Open time"])
df["Close time"] = pd.to_datetime(df["Close time"])

#### Set Close time as Index

In [5]:
df.set_index('Open time', inplace=True)

In [6]:
df.head()

,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
Open time,,,,,,,,,,,
2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999,5.993910e+06,5228,228.521921,3.090541e+06,0
2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999,5.154522e+06,4534,180.840403,2.430449e+06,0
2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999,5.710192e+06,4887,192.237935,2.558505e+06,0
2018-01-01 03:00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999,5.657448e+06,4789,137.918407,1.858041e+06,0
2018-01-01 04:00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999,4.588047e+06,4563,172.957635,2.328058e+06,0

#### ROC

In [7]:
def roc(df):
    df['roc_10'] = df['Close'].pct_change(periods=10) # *100 if we want percentages, right now it gives back decimals
    df['roc_21'] = df['Close'].pct_change(periods=21)

    return df # None? Not even sure if df needed / columns will be created without returning something

In [8]:
roc(df)

,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,roc_10,roc_21
Open time,,,,,,,,,,,,,
2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999,5.993910e+06,5228,228.521921,3.090541e+06,0,NaN,NaN
2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999,5.154522e+06,4534,180.840403,2.430449e+06,0,NaN,NaN
2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999,5.710192e+06,4887,192.237935,2.558505e+06,0,NaN,NaN
2018-01-01 03:00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999,5.657448e+06,4789,137.918407,1.858041e+06,0,NaN,NaN
2018-01-01 04:00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999,4.588047e+06,4563,172.957635,2.328058e+06,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-07 17:00:00,67783.63,67935.01,67768.97,67788.41,217.681040,2026-03-07 17:59:59.999,1.477294e+07,41860,146.943900,9.972905e+06,0,-0.000800,-0.004737
2026-03-07 18:00:00,67788.40,67788.41,67480.00,67568.13,1180.247820,2026-03-07 18:59:59.999,7.979030e+07,112179,388.463060,2.626513e+07,0,-0.003352,-0.010558
2026-03-07 19:00:00,67568.13,67572.35,66915.26,67080.34,1312.230200,2026-03-07 19:59:59.999,8.822703e+07,161182,521.428370,3.504474e+07,0,-0.013524,-0.018143
2026-03-07 20:00:00,67080.33,67437.50,67068.01,67402.98,590.471180,2026-03-07 20:59:59.999,3.975029e+07,85902,336.393160,2.264447e+07,0,-0.007032,-0.010439
2026-03-07 21:00:00,67402.98,67483.05,67281.34,67452.98,638.999950,2026-03-07 21:59:59.999,4.306520e+07,71562,290.969840,1.960855e+07,0,-0.008190,-0.012263

#### MACD

In [9]:
!pip install pandas_ta

Requirement already satisfied: pandas_ta in /Users/rajeevanrajendran/.pyenv/versions/3.12.9/envs/systematic_trading/lib/python3.12/site-packages (0.4.71b0)
Requirement already satisfied: numba==0.61.2 in /Users/rajeevanrajendran/.pyenv/versions/3.12.9/envs/systematic_trading/lib/python3.12/site-packages (from pandas_ta) (0.61.2)
Requirement already satisfied: numpy>=2.2.6 in /Users/rajeevanrajendran/.pyenv/versions/3.12.9/envs/systematic_trading/lib/python3.12/site-packages (from pandas_ta) (2.2.6)
Requirement already satisfied: pandas>=2.3.2 in /Users/rajeevanrajendran/.pyenv/versions/3.12.9/envs/systematic_trading/lib/python3.12/site-packages (from pandas_ta) (3.0.1)
Requirement already satisfied: tqdm>=4.67.1 in /Users/rajeevanrajendran/.pyenv/versions/3.12.9/envs/systematic_trading/lib/python3.12/site-packages (from pandas_ta) (4.67.3)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /Users/rajeevanrajendran/.pyenv/versions/3.12.9/envs/systematic_trading/lib/python3.12/site-packages (from numba==0.61.2->pandas_ta) (0.44.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rajeevanrajendran/.pyenv/versions/3.12.9/envs/systematic_trading/lib/python3.12/site-packages (from pandas>=2.3.2->pandas_ta) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/rajeevanrajendran/.pyenv/versions/3.12.9/envs/systematic_trading/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.3.2->pandas_ta) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python -m pip install --upgrade pip

In [10]:
# Quick logic for MACD in pandas
def MACD(df):
    ema_12 = df['Close'].ewm(span=12, adjust=False).mean()
    ema_26 = df['Close'].ewm(span=26, adjust=False).mean()

    df['macd_line'] = ema_12 - ema_26
    df['signal_line'] = df['macd_line'].ewm(span=9, adjust=False).mean()
    df['macd_histogram'] = df['macd_line'] - df['signal_line']

    return df

In [17]:
df['adx1'] = ta.adx(df['High'], df['Low'], df['Close'], length=14)['ADX_14']

In [11]:
def ADX(df):
    # Step 1 - True Range
    df['tr'] = pd.concat([
    df['High'] - df['Low'],
    (df['High'] - df['Close'].shift(1)).abs(),
    (df['Low'] - df['Close'].shift(1)).abs()
    ], axis=1).max(axis=1)

    # Step 2 - Directional Movement
    df['dm_plus'] = ((df['High'] - df['High'].shift(1)).clip(lower=0).where(
    (df['High'] - df['High'].shift(1)) > (df['Low'].shift(1) - df['Low']), 0))
    df['dm_minus'] = ((df['Low'].shift(1) - df['Low']).clip(lower=0).where(
    (df['Low'].shift(1) - df['Low']) > (df['High'] - df['High'].shift(1)), 0))

    # Step 3 - Smoothed averages (14-period)
    df['atr_14'] = df['tr'].ewm(span=14, adjust=False).mean()
    df['di_plus'] = 100 * df['dm_plus'].ewm(span=14, adjust=False).mean() / df['atr_14']
    df['di_minus'] = 100 * df['dm_minus'].ewm(span=14, adjust=False).mean() / df['atr_14']

    # Step 4 - ADX (final feature)
    df['dx'] = 100 * (df['di_plus'] - df['di_minus']).abs() / (df['di_plus'] + df['di_minus'])
    df['adx'] = df['dx'].ewm(span=14, adjust=False).mean()

    return df

In [12]:
MACD(df)

,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,roc_10,roc_21,macd_line,signal_line,macd_histogram
Open time,,,,,,,,,,,,,,,,
2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999,5.993910e+06,5228,228.521921,3.090541e+06,0,NaN,NaN,0.000000,0.000000,0.000000
2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999,5.154522e+06,4534,180.840403,2.430449e+06,0,NaN,NaN,-26.001709,-5.200342,-20.801368
2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999,5.710192e+06,4887,192.237935,2.558505e+06,0,NaN,NaN,-35.936476,-11.347569,-24.588908
2018-01-01 03:00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999,5.657448e+06,4789,137.918407,1.858041e+06,0,NaN,NaN,-36.940793,-16.466214,-20.474579
2018-01-01 04:00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999,4.588047e+06,4563,172.957635,2.328058e+06,0,NaN,NaN,-22.071801,-17.587331,-4.484470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-07 17:00:00,67783.63,67935.01,67768.97,67788.41,217.681040,2026-03-07 17:59:59.999,1.477294e+07,41860,146.943900,9.972905e+06,0,-0.000800,-0.004737,-378.440170,-464.519832,86.079662
2026-03-07 18:00:00,67788.40,67788.41,67480.00,67568.13,1180.247820,2026-03-07 18:59:59.999,7.979030e+07,112179,388.463060,2.626513e+07,0,-0.003352,-0.010558,-380.149203,-447.645706,67.496503
2026-03-07 19:00:00,67568.13,67572.35,66915.26,67080.34,1312.230200,2026-03-07 19:59:59.999,8.822703e+07,161182,521.428370,3.504474e+07,0,-0.013524,-0.018143,-416.068028,-441.330170,25.262143
2026-03-07 20:00:00,67080.33,67437.50,67068.01,67402.98,590.471180,2026-03-07 20:59:59.999,3.975029e+07,85902,336.393160,2.264447e+07,0,-0.007032,-0.010439,-413.730377,-435.810212,22.079835
2026-03-07 21:00:00,67402.98,67483.05,67281.34,67452.98,638.999950,2026-03-07 21:59:59.999,4.306520e+07,71562,290.969840,1.960855e+07,0,-0.008190,-0.012263,-403.195404,-429.287250,26.091846

In [13]:
ADX(df)

,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,...,signal_line,macd_histogram,tr,dm_plus,dm_minus,atr_14,di_plus,di_minus,dx,adx
Open time,,,,,,,,,,,,,,,,,,,,,
2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999,5.993910e+06,5228,228.521921,3.090541e+06,...,0.000000,0.000000,315.64,0.00,0.00,315.640000,0.000000,0.000000,NaN,NaN
2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999,5.154522e+06,4534,180.840403,2.430449e+06,...,-5.200342,-20.801368,440.51,0.00,244.63,332.289333,0.000000,9.815944,100.000000,100.000000
2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999,5.710192e+06,4887,192.237935,2.558505e+06,...,-11.347569,-24.588908,218.43,0.00,0.00,317.108089,0.000000,8.914423,100.000000,100.000000
2018-01-01 03:00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999,5.657448e+06,4789,137.918407,1.858041e+06,...,-16.466214,-20.474579,321.27,192.84,0.00,317.663010,8.094112,7.712337,2.415313,86.988708
2018-01-01 04:00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999,4.588047e+06,4563,172.957635,2.328058e+06,...,-17.587331,-4.484470,301.14,12.02,0.00,315.459942,7.571928,6.730704,5.881601,76.174427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-07 17:00:00,67783.63,67935.01,67768.97,67788.41,217.681040,2026-03-07 17:59:59.999,1.477294e+07,41860,146.943900,9.972905e+06,...,-464.519832,86.079662,166.04,45.33,0.00,295.330521,9.582936,22.356978,39.993976,44.650373
2026-03-07 18:00:00,67788.40,67788.41,67480.00,67568.13,1180.247820,2026-03-07 18:59:59.999,7.979030e+07,112179,388.463060,2.626513e+07,...,-447.645706,67.496503,308.41,0.00,288.97,297.074451,8.256457,32.231892,59.215640,46.592408
2026-03-07 19:00:00,67568.13,67572.35,66915.26,67080.34,1312.230200,2026-03-07 19:59:59.999,8.822703e+07,161182,521.428370,3.504474e+07,...,-441.330170,25.262143,657.09,0.00,564.74,345.076524,6.160213,45.869348,76.320336,50.556132
2026-03-07 20:00:00,67080.33,67437.50,67068.01,67402.98,590.471180,2026-03-07 20:59:59.999,3.975029e+07,85902,336.393160,2.264447e+07,...,-435.810212,22.079835,369.49,0.00,0.00,348.331654,5.288960,39.381943,76.320336,53.991359
2026-03-07 21:00:00,67402.98,67483.05,67281.34,67452.98,638.999950,2026-03-07 21:59:59.999,4.306520e+07,71562,290.969840,1.960855e+07,...,-429.287250,26.091846,201.71,45.55,0.00,328.782101,6.703540,36.160465,68.721823,55.955421