In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('btc_1hour_cleaned.csv')

In [4]:
df.head(3)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
0,2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999,5.993910e+06,5228,228.521921,3.090541e+06,0
1,2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999,5.154522e+06,4534,180.840403,2.430449e+06,0
2,2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999,5.710192e+06,4887,192.237935,2.558505e+06,0

In [5]:
df.shape

(71588, 12)

In [9]:
df.dtypes

Open time                        object
Open                            float64
High                            float64
Low                             float64
Close                           float64
Volume                          float64
Close time                       object
Quote asset volume              float64
Number of trades                  int64
Taker buy base asset volume     float64
Taker buy quote asset volume    float64
Ignore                            int64
forward_return                  float64
dtype: object

In [10]:
df['Open time'] = pd.to_datetime(df['Open time'])
df['Close time'] = pd.to_datetime(df['Close time'])

In [11]:
df.dtypes

Open time                       datetime64[ns]
Open                                   float64
High                                   float64
Low                                    float64
Close                                  float64
Volume                                 float64
Close time                      datetime64[ns]
Quote asset volume                     float64
Number of trades                         int64
Taker buy base asset volume            float64
Taker buy quote asset volume           float64
Ignore                                   int64
forward_return                         float64
dtype: object

In [13]:
df = df.set_index('Open time')

In [14]:
df.head(3)

,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,forward_return
Open time,,,,,,,,,,,,
2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999,5.993910e+06,5228,228.521921,3.090541e+06,0,0.002216
2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999,5.154522e+06,4534,180.840403,2.430449e+06,0,0.043728
2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999,5.710192e+06,4887,192.237935,2.558505e+06,0,0.018017

In [15]:
# Lookahead window - change this value to test different horizons
N = 5

# Step 1 - Forward return
df['forward_return'] = df['Close'].pct_change(periods=N).shift(-N)

In [16]:
df.head(20)

,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,forward_return
Open time,,,,,,,,,,,,
2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999,5.993910e+06,5228,228.521921,3.090541e+06,0,0.002216
2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999,5.154522e+06,4534,180.840403,2.430449e+06,0,0.043728
2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999,5.710192e+06,4887,192.237935,2.558505e+06,0,0.018017
2018-01-01 03:00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999,5.657448e+06,4789,137.918407,1.858041e+06,0,0.006708
2018-01-01 04:00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999,4.588047e+06,4563,172.957635,2.328058e+06,0,0.001175
2018-01-01 05:00:00,13615.20,13699.00,13526.50,13558.99,404.229046,2018-01-01 05:59:59.999,5.499055e+06,5086,142.331058,1.935710e+06,0,0.000813
2018-01-01 06:00:00,13539.00,13800.00,13510.00,13780.41,264.989684,2018-01-01 06:59:59.999,3.613408e+06,4072,126.077500,1.718753e+06,0,-0.040627
2018-01-01 07:00:00,13780.00,13818.55,13555.02,13570.35,292.188777,2018-01-01 07:59:59.999,4.002026e+06,4340,147.150029,2.016275e+06,0,-0.029323
2018-01-01 08:00:00,13569.98,13735.24,13400.00,13499.99,271.813553,2018-01-01 08:59:59.999,3.681944e+06,3733,122.809696,1.664737e+06,0,-0.035777
2018-01-01 09:00:00,13499.97,13670.00,13459.11,13616.99,213.095829,2018-01-01 09:59:59.999,2.893105e+06,3128,96.470199,1.309921e+06,0,-0.029786
2018-01-01 10:00:00,13632.00,13657.92,13497.98,13570.01,169.512196,2018-01-01 10:59:59.999,2.298369e+06,2769,68.490957,9.285741e+05,0,-0.023803
2018-01-01 11:00:00,13573.00,13589.89,13001.13,13220.56,665.334353,2018-01-01 11:59:59.999,8.777790e+06,7570,294.897441,3.888877e+06,0,-0.015322
2018-01-01 12:00:00,13220.56,13300.00,13056.23,13172.42,260.492708,2018-01-01 12:59:59.999,3.437453e+06,3618,115.163640,1.519720e+06,0,-0.011419
2018-01-01 13:00:00,13150.05,13200.41,12815.70,13017.00,451.901126,2018-01-01 13:59:59.999,5.869105e+06,5719,248.601776,3.228414e+06,0,0.009065
2018-01-01 14:00:00,12999.71,13245.00,12750.00,13211.39,692.467362,2018-01-01 14:59:59.999,8.951403e+06,7132,299.429608,3.872687e+06,0,0.002194
2018-01-01 15:00:00,13211.39,13330.00,13120.38,13247.00,427.071957,2018-01-01 15:59:59.999,5.654630e+06,4888,167.119723,2.212216e+06,0,0.011492
2018-01-01 16:00:00,13247.00,13247.08,12966.42,13018.00,367.393566,2018-01-01 16:59:59.999,4.818678e+06,4004,184.967309,2.426692e+06,0,0.035567
2018-01-01 17:00:00,13018.00,13198.98,13000.00,13022.00,228.572028,2018-01-01 17:59:59.999,2.993657e+06,2978,119.944127,1.570737e+06,0,0.033021
2018-01-01 18:00:00,13007.87,13256.28,12940.00,13135.00,244.366755,2018-01-01 18:59:59.999,3.210341e+06,3267,110.346010,1.449282e+06,0,0.018652
2018-01-01 19:00:00,13135.00,13290.65,13106.61,13240.37,252.004885,2018-01-01 19:59:59.999,3.326195e+06,2929,142.196333,1.877608e+06,0,0.038491

In [18]:
# Step 2 - Binary Label
df['label'] = (df['forward_return'] > 0).astype(int)
# 1 - BUY, 2 - SELL

In [20]:
df.head(20)

,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,forward_return,label
Open time,,,,,,,,,,,,,
2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999,5.993910e+06,5228,228.521921,3.090541e+06,0,0.002216,1
2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999,5.154522e+06,4534,180.840403,2.430449e+06,0,0.043728,1
2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999,5.710192e+06,4887,192.237935,2.558505e+06,0,0.018017,1
2018-01-01 03:00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999,5.657448e+06,4789,137.918407,1.858041e+06,0,0.006708,1
2018-01-01 04:00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999,4.588047e+06,4563,172.957635,2.328058e+06,0,0.001175,1
2018-01-01 05:00:00,13615.20,13699.00,13526.50,13558.99,404.229046,2018-01-01 05:59:59.999,5.499055e+06,5086,142.331058,1.935710e+06,0,0.000813,1
2018-01-01 06:00:00,13539.00,13800.00,13510.00,13780.41,264.989684,2018-01-01 06:59:59.999,3.613408e+06,4072,126.077500,1.718753e+06,0,-0.040627,0
2018-01-01 07:00:00,13780.00,13818.55,13555.02,13570.35,292.188777,2018-01-01 07:59:59.999,4.002026e+06,4340,147.150029,2.016275e+06,0,-0.029323,0
2018-01-01 08:00:00,13569.98,13735.24,13400.00,13499.99,271.813553,2018-01-01 08:59:59.999,3.681944e+06,3733,122.809696,1.664737e+06,0,-0.035777,0
2018-01-01 09:00:00,13499.97,13670.00,13459.11,13616.99,213.095829,2018-01-01 09:59:59.999,2.893105e+06,3128,96.470199,1.309921e+06,0,-0.029786,0
2018-01-01 10:00:00,13632.00,13657.92,13497.98,13570.01,169.512196,2018-01-01 10:59:59.999,2.298369e+06,2769,68.490957,9.285741e+05,0,-0.023803,0
2018-01-01 11:00:00,13573.00,13589.89,13001.13,13220.56,665.334353,2018-01-01 11:59:59.999,8.777790e+06,7570,294.897441,3.888877e+06,0,-0.015322,0
2018-01-01 12:00:00,13220.56,13300.00,13056.23,13172.42,260.492708,2018-01-01 12:59:59.999,3.437453e+06,3618,115.163640,1.519720e+06,0,-0.011419,0
2018-01-01 13:00:00,13150.05,13200.41,12815.70,13017.00,451.901126,2018-01-01 13:59:59.999,5.869105e+06,5719,248.601776,3.228414e+06,0,0.009065,1
2018-01-01 14:00:00,12999.71,13245.00,12750.00,13211.39,692.467362,2018-01-01 14:59:59.999,8.951403e+06,7132,299.429608,3.872687e+06,0,0.002194,1
2018-01-01 15:00:00,13211.39,13330.00,13120.38,13247.00,427.071957,2018-01-01 15:59:59.999,5.654630e+06,4888,167.119723,2.212216e+06,0,0.011492,1
2018-01-01 16:00:00,13247.00,13247.08,12966.42,13018.00,367.393566,2018-01-01 16:59:59.999,4.818678e+06,4004,184.967309,2.426692e+06,0,0.035567,1
2018-01-01 17:00:00,13018.00,13198.98,13000.00,13022.00,228.572028,2018-01-01 17:59:59.999,2.993657e+06,2978,119.944127,1.570737e+06,0,0.033021,1
2018-01-01 18:00:00,13007.87,13256.28,12940.00,13135.00,244.366755,2018-01-01 18:59:59.999,3.210341e+06,3267,110.346010,1.449282e+06,0,0.018652,1
2018-01-01 19:00:00,13135.00,13290.65,13106.61,13240.37,252.004885,2018-01-01 19:59:59.999,3.326195e+06,2929,142.196333,1.877608e+06,0,0.038491,1

In [21]:
df['label'].value_counts()

label
1    36706
0    34882
Name: count, dtype: int64